# Generated by Django 2.2.3 on 2019-08-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190722_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Middle_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
